# This is a YAML file.
#
# The most important parameter is a dict of filters. These are named,
# and must have cwl, fwhm parameters. Transmission ratio ("transmission")
# and position fields are optional.
# 

filters:
    red:
        position:   L01         # if not provided, the name is used again.
        transmission:   1.0     # this is the default
        cwl:        440
        fwhm:       30
    green:
        cwl:        540
        position:   L02         # ordering isn't important
        fwhm:       30
    blue:
        cwl:        440
        fwhm:       30
