"""Test that the sources of ROIs end up on the images they are applied to, so that
data derived from an ROI can be traced back to where that ROI came from."""

import pcot
from fixtures import *
from pcot.datum import Datum
from pcot.document import Document


def roiexpr_doc(expr, emptyROI=False):
    """Build a graph where input 0 goes through a roidq node to generate an ROI (whose sources are
    input 0's) which is fed into a roiexpr node as 'p'. The roiexpr node's image comes from input 1.
    Returns the roiexpr node after running."""
    pcot.setup()
    doc = Document()
    # SAT is a BAD bit, so roidq's default parameters will give an ROI covering the whole image - unless
    # we want an empty ROI, in which case there are no DQ bits and the ROI will be empty.
    d = (dq.NONE, dq.NONE, dq.NONE) if emptyROI else (dq.SAT, dq.NONE, dq.NONE)
    assert doc.setInputDirectImage(0, genrgb(8, 8, 1, 2, 3, d=d, inpidx=0)) is None
    assert doc.setInputDirectImage(1, genrgb(8, 8, 4, 5, 6, inpidx=1)) is None

    roidq = doc.graph.create("roidq")
    roidq.connect(0, doc.graph.create("input 0"), 0)

    node = doc.graph.create("roiexpr")
    node.connect(0, doc.graph.create("input 1"), 0)
    node.connect(1, roidq, 1)
    node.params.expr = expr
    doc.run()
    return node


def inputIndices(sourceset):
    return {s.inputIdx for s in sourceset.getSources()}


def test_roiexpr_roi_sources_on_image():
    """The sources of the ROI generated by a roiexpr node are added to every band of its output image"""
    node = roiexpr_doc("p")
    assert node.error is None

    roi = node.outputs[1]
    assert roi.tp == Datum.ROI
    assert inputIndices(roi.sources) == {0}

    img = node.getOutput(0, Datum.IMG)
    assert len(img.sources) == 3
    for ss in img.sources:
        assert inputIndices(ss) == {0, 1}


def test_roiexpr_non_roi_expression_is_an_error():
    """An expression which doesn't produce an ROI gives a clear error"""
    node = roiexpr_doc("1")
    assert node.error is not None
    assert "does not produce an ROI" in node.error.message


def test_roiexpr_empty_painted_roi():
    """An empty painted ROI (here from a roidq node which matches no pixels) can be used in a roiexpr node,
    giving an empty ROI rather than crashing."""
    node = roiexpr_doc("p", emptyROI=True)
    assert node.error is None
    roi = node.outputs[1].get(Datum.ROI)
    assert roi is not None
    assert roi.pixels() == 0


def test_roidq_roi_sources_on_image():
    """Issue #68: an ROI generated by roidq from one band (here R) and used in a calculation on another
    band (here G) must add its sources to the result. The graph is the one in the issue:
    RGB -> dqmod (set SAT where R > 0.5) -> roidq (from band R) -> expr "a$G*10"."""
    pcot.setup()
    doc = Document()
    img = genrgb(8, 8, 0, 0.2, 0.3)
    img.img[:, :4, 0] = 1.0     # R > 0.5 only in the left half
    assert doc.setInputDirectImage(0, img) is None

    dqmod = doc.graph.create("dqmod")
    dqmod.connect(0, doc.graph.create("input 0"), 0)
    dqmod.params.val = 0.5
    dqmod.params.test = 'gt'
    dqmod.params.band = 0
    dqmod.params.dq = dq.SAT

    roidq = doc.graph.create("roidq")
    roidq.connect(0, dqmod, 0)
    roidq.params.band = 0

    expr = doc.graph.create("expr")
    expr.connect(0, roidq, 0)
    expr.params.expr = "a$G*10"
    doc.run()

    for n in (dqmod, roidq, expr):
        assert n.error is None
    out = expr.getOutput(0, Datum.IMG)

    # the ROI was applied: G is multiplied up only where R > 0.5
    assert np.allclose(out.img[:, :4], 2.0)
    assert np.allclose(out.img[:, 4:], 0.2)

    # and the result depends on R as well as G
    assert len(out.sources) == 1
    assert {s.band for s in out.sources[0].getSources()} == {'R', 'G'}


def test_inset_roi_sources_on_image():
    """The ROI which positions an inset adds its sources to every band of the output, along with
    those of the background and inset images."""
    pcot.setup()
    doc = Document()
    assert doc.setInputDirectImage(0, genrgb(16, 16, 0.1, 0.2, 0.3, inpidx=0)) is None     # background
    assert doc.setInputDirectImage(1, genrgb(4, 4, 0.4, 0.5, 0.6, inpidx=1)) is None       # inset
    # SAT everywhere, so roidq gives an ROI covering all of input 2 (the same size as the background)
    assert doc.setInputDirectImage(2, genrgb(16, 16, 1, 2, 3, d=(dq.SAT, dq.NONE, dq.NONE), inpidx=2)) is None

    roidq = doc.graph.create("roidq")
    roidq.connect(0, doc.graph.create("input 2"), 0)

    inset = doc.graph.create("inset")
    inset.connect(0, doc.graph.create("input 0"), 0)
    inset.connect(1, doc.graph.create("input 1"), 0)
    inset.connect(2, roidq, 1)
    doc.run()

    assert inset.error is None
    img = inset.getOutput(0, Datum.IMG)
    assert len(img.sources) == 3
    for ss in img.sources:
        assert inputIndices(ss) == {0, 1, 2}
