"""Test that the sources of ROIs end up on the images they are applied to, so that
data derived from an ROI can be traced back to where that ROI came from."""

import pcot
from fixtures import *
from pcot.datum import Datum
from pcot.document import Document


def roiexpr_doc(expr, emptyROI=False):
    """Build a graph where input 0 goes through a roidq node to generate an ROI (whose sources are
    input 0's) which is fed into a roiexpr node as 'p'. The roiexpr node's image comes from input 1.
    Returns the roiexpr node after running."""
    pcot.setup()
    doc = Document()
    # SAT is a BAD bit, so roidq's default parameters will give an ROI covering the whole image - unless
    # we want an empty ROI, in which case there are no DQ bits and the ROI will be empty.
    d = (dq.NONE, dq.NONE, dq.NONE) if emptyROI else (dq.SAT, dq.NONE, dq.NONE)
    assert doc.setInputDirectImage(0, genrgb(8, 8, 1, 2, 3, d=d, inpidx=0)) is None
    assert doc.setInputDirectImage(1, genrgb(8, 8, 4, 5, 6, inpidx=1)) is None

    roidq = doc.graph.create("roidq")
    roidq.connect(0, doc.graph.create("input 0"), 0)

    node = doc.graph.create("roiexpr")
    node.connect(0, doc.graph.create("input 1"), 0)
    node.connect(1, roidq, 1)
    node.params.expr = expr
    doc.run()
    return node


def inputIndices(sourceset):
    return {s.inputIdx for s in sourceset.getSources()}


def test_roiexpr_roi_sources_on_image():
    """The sources of the ROI generated by a roiexpr node are added to every band of its output image"""
    node = roiexpr_doc("p")
    assert node.error is None

    roi = node.outputs[1]
    assert roi.tp == Datum.ROI
    assert inputIndices(roi.sources) == {0}

    img = node.getOutput(0, Datum.IMG)
    assert len(img.sources) == 3
    for ss in img.sources:
        assert inputIndices(ss) == {0, 1}


def test_roiexpr_non_roi_expression_is_an_error():
    """An expression which doesn't produce an ROI gives a clear error"""
    node = roiexpr_doc("1")
    assert node.error is not None
    assert "does not produce an ROI" in node.error.message


def test_roiexpr_empty_painted_roi():
    """An empty painted ROI (here from a roidq node which matches no pixels) can be used in a roiexpr node,
    giving an empty ROI rather than crashing."""
    node = roiexpr_doc("p", emptyROI=True)
    assert node.error is None
    roi = node.outputs[1].get(Datum.ROI)
    assert roi is not None
    assert roi.pixels() == 0
