import argparse,logging
from latex import LatexProcessor
from mark import MarkdownProcessor
import datetime

parser = argparse.ArgumentParser(description="List the unit tests")

parser.add_argument('-f', '--format', help="Format of output", metavar="FORMAT", type=str, default="md")
parser.add_argument('-d', '--dir', help="Directory to run pytest in", metavar="DIR", type=str, default='~/PCOT/tests')
parser.add_argument('--debug', help="Debug level", metavar="DEBUG", type=str, default='info')
parser.add_argument('--full', '--fullname','--fullnames', help="Show full names (i.e. paths) of tests", dest='fullname',action='store_true')

args=parser.parse_args()

lev = logging.getLevelName(args.debug.upper())
if type(lev) != int:
    raise(Exception(f"unknown debug level: {args.debug}"))

logging.basicConfig(format='%(levelname)s %(asctime)s %(name)s: %(message)s', force=True)
logging.getLogger().setLevel(lev)

opts = { 
    'dir': args.dir,
    'fullname': args.fullname
}

formats = {
    'html': lambda: MarkdownProcessor(opts, True),
    'md': lambda: MarkdownProcessor(opts, False),
    'tex': lambda: LatexProcessor(opts),
    'latex': lambda: LatexProcessor(opts),
}

    
if args.format not in formats:
    raise(Exception(f"Unknown format: {args.format}"))

f = formats[args.format]()



date = datetime.datetime.now().isoformat()
f.preamble(f"Automatic test listing generated by testlister.py at {date}")

print(f.run())


