@startuml
skinparam classAttributeIconSize 0

abstract class ROI {
}

note top of ROI
region of interest
abstract class
end note

class ROIRect extends ROI {
}
note bottom of ROIRect
example concrete
region class
end note

class ChannelMapping {
}
note bottom of ChannelMapping
defines how an image
is viewed as RGB
end note

class ImageCube {
}
note right of ImageCube
the image / data cube
core type: the most
common data passed
between nodes
end note

ImageCube *-- "1..1" MultiBandSource: "sources: set of sources\nper band/channel"
ImageCube o-- "0..1" ChannelMapping: rgbMapping
ImageCube *-- ndarray : img
ImageCube *-- ndarray : uncertainty
ImageCube *-- ndarray : dq
ImageCube *-- "0..*" ROI : rois

note bottom of ndarray
numpy arrays - all have the same shape
               h x w x bands
               **OR** h x w (if there is
               only 1 band)

img : actual image data (32-bit float)
uncertainty : uncertainty data (32-bit float)
dq : data quality and other info bits (16-bit int)
end note

@enduml

