@startuml
skinparam classAttributeIconSize 0

abstract class ROI <<abstract>> {
}

class ROIRect extends ROI {
}

class SubImageCubeROI {
    +fullmask():ndarray<bool>
    +cropother(img:ImageCube):ImageCube
    
}

SubImageCubeROI o-- ImageCube:img

class ImageCube {
    +subimage():SubImageCubeROI
    +modifyWithSub(subimage:SubImageCubeROI,newimg:ndarray<float>)
}

ImageCube *-- "0..*" ROI : rois




@enduml

