@startuml
skinparam classAttributeIconSize 0

abstract class ROI <<abstract>> {
}

class ROIRect extends ROI {
}

class SubImageCube {
    +fullmask():ndarray<bool>
    +cropother(img:ImageCube):ImageCube
    
}

SubImageCube o-- ImageCube:img

class ImageCube {
    +subimage():SubImageCube
    +modifyWithSub(subimage:SubImageCube,newimg:ndarray<float>)
}

ImageCube *-- "0..*" ROI : rois




@enduml

