@startuml
skinparam classAttributeIconSize 0

class XForm {
    +inputs:List<Tuple<XForm,int>>
}

class XFormType {
    +{static} allTypes: XFormType
}

XFormType *-- "0..n" XFormType : allTypes

XFormGraph *-- "0..n" XForm

XFormType o-- "0..n" XForm : instances

XForm o-- XFormType : type 

XformNormImage -up-|> XFormType
XformRect -up-|> XFormType

XformRect ..|> TabRect: creates
XformNormImage ..|> TabImage: creates

TabImage -up-|> Tab
TabRect -up-|> Tab


Tab o-- XForm:node

XForm *-- "0..n" Tab


@enduml
