import pcot
import os
import shutil

header = """
# Autodocs
Below are automatically generated documents for certain entities
in PCOT. These are generated by running the *genhelp.py*
script in the mkdocs directory.
"""

exprheader1 = """
## *Expr* functions
Below are functions which can be used in the expression evaluation
node, [expr](expr).
"""

exprheader2 = """
## *Expr* properties
Below are properties which can be used in the expression evaluation
node, [expr](autodocs/expr).
Properties are names which can be used as identifiers on the
right hand side of a "." operator, such as *a.w* to get the width of an
image *a*.
"""

pcot.xform.createXFormTypeInstances()

parser = pcot.xform.allTypes['expr'].parser


if os.path.exists('docs/autodocs'):
    shutil.rmtree('docs/autodocs')

os.makedirs('docs/autodocs')

def genNodes(idxfile):
    idxfile.write("## Nodes\n\n")
    for realname, x in pcot.xform.allTypes.items():
        name=realname.replace(' ', '_')
        idxfile.write(f"* [{realname}]({name})\n")
        print(name)
        with open(f"docs/autodocs/{name}.md","w") as file:
            file.write(pcot.ui.help.getHelpMarkdown(x))
            
def genFuncs(idxfile):
    idxfile.write("### Functions\n\n")
    md = parser.listFuncs()
    idxfile.write(md)
    
def genProps(idxfile):
    idxfile.write("### Properties\n\n")
    md = parser.listProps()
    idxfile.write(md)

with open("docs/autodocs/index.md","w") as idxfile:
    idxfile.write(header+"\n\n")
    genNodes(idxfile)
    idxfile.write(exprheader1)
    genFuncs(idxfile)      
    idxfile.write(exprheader2)
    genProps(idxfile)
